language: node_js
node_js:
- 4.4.1
sudo: false
env:
  global:
  - secure: PKoZxdUSCUgiNCCcocezhvRAFv2bB4Zshfp2RqWC1WtnKcFh+UKueMMDHhk5FTzfioXA32rVOcma1fvEoocai6kQi0kpwhkPLK46IONJGKaPMMSBsbgrocR1jouXLmnygz19JkdiXjwlmERQb6dLlCIJ/LZ/VesqwFJARQzFljk7MXRoXLcn4XvWE1KTcjFjA2ySGzzfVpbBlqeDm7ss18/Pw27LJUDMsi2h9W/pJq4XAsAJuGTQI5mQLYv0r4u/yRP2VAGts6+VbGArKWB8gEPDlaLGX0htCxnhbra1sm90HZJqv/+EQ6ayRH7ktrkJuKAWygilLcqOWMzQdNVyHOtzufbGvVDjkgKGotLr8C6DZxx9Ktn7TwyM0N2uvlhxHCPr0C4OxyqNRXg1ICCUG4rVcZx2ZzNbPiulO6OJpi94vmdJg+Y0nTYL0gNDbEsR/MrrflIy4fedng4xVV3r59m2jKbMosIiY9+FWzoZmxijYgRriOn7fjy/WexP1Dvh7xAhHT67LjVjAPEVCwdu394gcKHSr2JhfIRCK9REfrJSKYunKcmlCoN1zXuqwSbJCzPEf9LefKUyhv1rqDQrCAiR/nbsgd6xWLPCker7ss+mHizZ1QVlbmH0CSO3HttbxAw5uVUEc39G1oxjxnfvOL/x5ClVtwdtroP0mednajg=
  - secure: vv/UdQ3aImh8iorFsZZg3P2uTdfoSceVB6AM648P025DfF823Kw9iOe9/K3iF46Td1nbmdgFvTlP4tP70UizAa6pSSxmlzbpdU0MTXzLl+LFFIcr2OBaPnKold0PRLQOjybCmXJZg/2sOxJp9Bzwu51PF9v4V8XZLQAHDPcTkVPOvKOic09xV240aWmhGZkGD47UPjBvRd8BFVS7ZxRX9m3rWktDwDXcegW4a1iQfqnPVa78xurDCSjJFkt0HJI/de9M5H4dcR0qgPxJkLEtaKwA2rbNbAfXfC8Wvoe15yuW5ByE1m2O/XP8F5unBiEe9nAguns5+qnN/cID5zGd7q7Zgh6CphRaBe9WmjZCml7PKSDNK+xS4znfc2ap+8WSlX9+3n4uiahtDwuoWv0WHZO8LfEQY1Jv1me4D8vKkbJBYRpKLab7pzXGWgThj5p/0a1bjtux/M/USypSstnZwMFn6aWYccKYZVnGxH8b3aeKgvW6DNc4m81RN+EcTJ+2IkRv2gtOqOUDj1yJ3GhRauqUFIUg6fFIUw286slpr76LUrc05XZ4u3dyYl8yIu8LrnF1Oqbz98gf0hgfkdygl/emXq08n2b8vL3av/ncq/k3ju6RUY1+bZnlKWfD/AdwDsbnTIbI3k7W3OldYMfhHpwZIm6I7dP4H0lUxxHHobg=

addons:
  sauce_connect: true
  apt:
    packages:
    - make
    - time

before_script:
  - npm install -g gulp

before_deploy: gulp build

deploy:
  - provider: releases
    api_key:
      secure: AU1/iViO8QdqPpPfb6vUsSoENfwxSwPI0zRs285iX3g8H51JP77TgOwO7qBy1uIz7IgTwo8goWnaObA0ey74LDs/vD6n3cPBaeyg7OJO5Kxfr70D1IuPuQcmMbdcpkP+crNGp2xTKGpIX6s+7YXq92uAi7+2J7YYXpAtMVCOWXmqqAF8D8eE7Ww0ecobatOgtcQZbsA44wkurC2eIXUs0g9Cn4uXLB4m9lD1SHYoWq+g8O17h9u3pKZ6hue9udc3zm7sH4w2tqqsKKin658SbOuwsPQ2BuypBO2m2SBjuVpUSLTP7uigPh+PmKi8eMdQI5ofYRRcYDMqNoEzlUNMweP6mB9zGmVxKARsJ7MlPfl0WM2MaIwK/SITlFOk0IcbEF6lG0r+PfLdHgasyUcYjWj/nkZ+50Gt8F9Kab4IcRWT+c3A4eP+vr20MtwOhKATlFG9aOUFTr9Xesqw5eW5gfEm90nkAsEXjpbD390AaWlHJiTSWL/8mPqTaiyRp4pBZTec5IRcVfkFhKju+WdssRukRa0F/g1vA93eOmBATQooBArmErU+HzF4+7UdVpWFN3KwQokqyE5fvuCctLd7Wc70UvSz6hsg02eRWG9QVTytBK5DItPW9wkxNcAHvuM5e1oT3lXgCBRXYYubAQI5gnjiDRVdw2iP9ENVGtL0FaQ=
    file:
      - dist/chassis.x.min.js
      - dist/chassis.x.dev.js
      - dist/httpproxy.min.js
      - dist/controller.min.js
      - dist/state.min.js
      - bower.json
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "sysadmin@coreybutler.com"
    api_key:
      secure: "DX5+elX/qy/hHEBZl5NibIDgkp/XE5Ul9VQd4LMfnb8pTTt4qAX1yVI6bjoEnUWOjwqp/5BSDLws619FYAQYIO4jQznS62ZBd8kkSUHqHBvtHmKOCt6zwnMze+IK/oQjw5iau7mPouOgL8d7WRZocvUyTT5Tu69cadPx27A685VlYO12Sfr11B33++y/OdJWSodQ6rYBxArFDoq9H+xF7ADbnE97g2yQZoUgzFFTsucTUFlY5+nM5uyRJDjsdAPbfRd8D9pYAoNWs4O8SM5u48/PpjNGWuWmCmSgWooo+VkR5hUPOn9QHQ0fgrJ7WsJpFQKwtgXJLfXJDeucuyqWa9wkrvNt6ZkNcLLF3J4G0N3GTAHLVHuaUqoPOkaf5RXLgf6hLNYfHghqdj5cVZnE1zxJNNCWObC4DQJkx/EkyX+7G2Us7FwIUBhZVFiKuBpaGo+sCI01vOcjGiumF5sfV9ZvIiJMsakSHsMuDU+Ki73AUkipc0IAo4lSEvKwgVK6yfOVLCqquyiXoFrqx8Wrind2Yeu+1sdGupJosFlkhHVQwGvTfbrwmSCKuu8Zx/oE//ctp1ZV6oowcc60zO/3XEeaB56SUF8sI61GLWc+1JPrpB9NlgS1xwJjxPoJtWD5V9EoCwI4DcCOiuyMbaQ+WfBj3EG4VHWvKoV57fdXWCw="
    on:
      tags: true
cache:
  directories:
    - node_modules
