language: node_js
node_js:
- 4.4.1
sudo: false
env:
  global:
  - secure: b3SiSHLCL0rhlijN8CwOSbUxZetrtKz3ylR0rOg/8P8phluZLZp7lNrgU7ov5xj3FFrM7YQZ4HSRo+TB1nX5q2iM+VlNyTkoyiWKHCqEi4wLDB+8Bd1TozZsslrKnjbHMII1rIIIM0YwfUMWJ638QhrUNzIwyxy3oPQC8SIxLei+q3Td+wCgQ9Vv9XqM6ZNL/gZ4uvZ9z6zX0QWWpIrek0MqCogJmMlw8cjwX1VwMfKnZSZTtLgNUUSmlY8uISOKhZ+RQLM313phUvKtMc1ll2IXg6wUV6sTEHExTVPIxzWQzs1Vya7h1qXyZ0XwJeDhblgHk7p3NZGWQnNanOji9xrsA/TzYvEeuTMVyz6O1PJTUIHx4cSmGBGEDr87+bzLiUV9HvlL1RXIbPPp/wIddY9RyZZokg3Bakipkmer24JLvwi7AR5eQNwXosz4oeGxCvhOrrZV4REUrZEZplNQ6ONPJ3ZWhY6y6Jq9t8LvpghFBPlZNHajPA/QaQhHX67a5xfMg1UvdqIk6fXEFFGnfa63qUdZxTAkcO7YsivQaoiFDfJC7UHBT1ShyoQfNHSyiNvPHyDmFn7twF0KEeHd0SdzRLIoNVWQSjEOJoy8R3dICxSo8JmpAadk8qVBQgrA8JNogtSyGzSly2c5ywYGe338D3n+nH/tLHFNPKmlrhk=
  - secure: msmfnjz7M8ZGhBgEo/CvHDbwgLHcAoYUCD1DprMVo6cUneWBTPecvBSm0dY6ny/evzleIhGBos+01un9qMfbXkQzc/b1rzrtI7N8OFlagy2ivFHq+D8nj1elDBV8hSP0Hf7IlhI7r6maDDO355bCLD60mDycOdXLLq/98E2yq5jUCKwNZaUYDsnYZT5JbO8QqaPnbYFitKgfUHqyA/EEVNojYpBe01UNMTFheJLDNnuOpwvrhbpdH6P7wOKwLeQ82aNUrK7Q+zulJVLiEFHgsS1I+uXX72jCSz7Anb2DBLWw1NeTZDDU0CHHMoSNIpZ8IaqG1Xsp1EIkCossg37LotXWxRl3sCtTZIpIa17vi0y/HQJv8aeiSpGEp1HysYAROEdePTwelA6UuTli9JJNIXPl6gCAegTIU0lOQLPgowP5910xHMyC8p73b1CvLT2HQdq4iN2Au+3P5bP69vnxh9xhsHEq1WMQEeSZdt4SzK4GAVBCvMlTkLzWYVMB1rzqbnMbkV/Dh1PBz+QWWjzV16V4oJCZYxjXtM5voRX3lGgavP8uE8pBWD75wDLKTCqcnfFqm/r/CBIk4R7nqeKZatxyhFBYf4c/N8yw+jKR1nmP0xcMMwOM0Z3DvRpelmWkfUf9a7AQCoJPWDLtyjMddlCGk52roqPNRJicl3D8rOA=
addons:
  sauce_connect: true
  apt:
    packages:
    - make
    - time

before_script:
  - npm install -g gulp

before_deploy: gulp build

deploy:
  - provider: releases
    api_key:
      secure: AU1/iViO8QdqPpPfb6vUsSoENfwxSwPI0zRs285iX3g8H51JP77TgOwO7qBy1uIz7IgTwo8goWnaObA0ey74LDs/vD6n3cPBaeyg7OJO5Kxfr70D1IuPuQcmMbdcpkP+crNGp2xTKGpIX6s+7YXq92uAi7+2J7YYXpAtMVCOWXmqqAF8D8eE7Ww0ecobatOgtcQZbsA44wkurC2eIXUs0g9Cn4uXLB4m9lD1SHYoWq+g8O17h9u3pKZ6hue9udc3zm7sH4w2tqqsKKin658SbOuwsPQ2BuypBO2m2SBjuVpUSLTP7uigPh+PmKi8eMdQI5ofYRRcYDMqNoEzlUNMweP6mB9zGmVxKARsJ7MlPfl0WM2MaIwK/SITlFOk0IcbEF6lG0r+PfLdHgasyUcYjWj/nkZ+50Gt8F9Kab4IcRWT+c3A4eP+vr20MtwOhKATlFG9aOUFTr9Xesqw5eW5gfEm90nkAsEXjpbD390AaWlHJiTSWL/8mPqTaiyRp4pBZTec5IRcVfkFhKju+WdssRukRa0F/g1vA93eOmBATQooBArmErU+HzF4+7UdVpWFN3KwQokqyE5fvuCctLd7Wc70UvSz6hsg02eRWG9QVTytBK5DItPW9wkxNcAHvuM5e1oT3lXgCBRXYYubAQI5gnjiDRVdw2iP9ENVGtL0FaQ=
    file:
      - dist/chassis.x.min.js
      - dist/chassis.x.dev.js
      - dist/httpproxy.min.js
      - dist/driver.min.js
      - dist/state.min.js
      - bower.json
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "sysadmin@coreybutler.com"
    api_key:
      secure: "DX5+elX/qy/hHEBZl5NibIDgkp/XE5Ul9VQd4LMfnb8pTTt4qAX1yVI6bjoEnUWOjwqp/5BSDLws619FYAQYIO4jQznS62ZBd8kkSUHqHBvtHmKOCt6zwnMze+IK/oQjw5iau7mPouOgL8d7WRZocvUyTT5Tu69cadPx27A685VlYO12Sfr11B33++y/OdJWSodQ6rYBxArFDoq9H+xF7ADbnE97g2yQZoUgzFFTsucTUFlY5+nM5uyRJDjsdAPbfRd8D9pYAoNWs4O8SM5u48/PpjNGWuWmCmSgWooo+VkR5hUPOn9QHQ0fgrJ7WsJpFQKwtgXJLfXJDeucuyqWa9wkrvNt6ZkNcLLF3J4G0N3GTAHLVHuaUqoPOkaf5RXLgf6hLNYfHghqdj5cVZnE1zxJNNCWObC4DQJkx/EkyX+7G2Us7FwIUBhZVFiKuBpaGo+sCI01vOcjGiumF5sfV9ZvIiJMsakSHsMuDU+Ki73AUkipc0IAo4lSEvKwgVK6yfOVLCqquyiXoFrqx8Wrind2Yeu+1sdGupJosFlkhHVQwGvTfbrwmSCKuu8Zx/oE//ctp1ZV6oowcc60zO/3XEeaB56SUF8sI61GLWc+1JPrpB9NlgS1xwJjxPoJtWD5V9EoCwI4DcCOiuyMbaQ+WfBj3EG4VHWvKoV57fdXWCw="
    on:
      tags: true
cache:
  directories:
    - node_modules
